### ISSUE TITLE
tensorboardX path

### ISSUE THREAD

**Issue by Supernova410** [weiaicunzai/pytorch-cifar100#24]
Traceback (most recent call last):
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\tensorboardX\record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'runs\\vgg16\\2020-03-08T16'

**Comment by YYsmith** [comment]
I also meet this problem. How can I solve it?

**Comment by Ken-JKK** [comment]
Traceback (most recent call last):
  File "C:\Users\JY\Anaconda3\lib\site-packages\tensorboardX\record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'runs\\vgg16\\2020-04-18T16'

I also meet this problem.

**Comment by bokveizen** [comment]
Modifying the TIME_NOW variable in conf/golbal_setting may solve the problem

**Comment by weiaicunzai** [comment]
hello, guys, already fixed this bug at #1 , plz update the code, thanks.
