### ISSUE TITLE
How do I change to my own data set

### ISSUE THREAD

**Issue by 15826694153** [weiaicunzai/pytorch-cifar100#36]
My data set has three categories in three folders. How can I change the code that reads the data

**Comment by weiaicunzai** [comment]
If your dataset is a image classification dataset, you could implement your own dataset class to read your data.

see more details here:
https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset

**Comment by chejulien** [comment]
> 
> 
> If your dataset is a image classification dataset, you could implement your own dataset class to read your data.
> 
> see more details here:
> https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset

I tried implement my dataset class, seems like loading goes well but there was an error when I trained, not sure whether you met this before, thanks in advance, here the message:

Traceback (most recent call last):
  File "train.py", line 209, in <module>
    train(epoch)
  File "train.py", line 44, in train
    outputs = net(images)
  File "E:\Software\Anaconda\envs\labelme\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\learning\pytorch-cifar100\pytorch-cifar100\models\vgg.py", line 40, in forward
    output = self.classifier(output)
  File "E:\Software\Anaconda\envs\labelme\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Software\Anaconda\envs\labelme\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "E:\Software\Anaconda\envs\labelme\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Software\Anaconda\envs\labelme\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "E:\Software\Anaconda\envs\labelme\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by chejulien** [comment]
> 
> 
> If your dataset is a image classification dataset, you could implement your own dataset class to read your data.
> 
> see more details here:
> https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset

I tried implement my dataset class, seems like loading goes well but there was an error when I trained, not sure whether you met this before, thanks in advance, here the message:

Traceback (most recent call last):
File "train.py", line 209, in
train(epoch)
File "train.py", line 44, in train
outputs = net(images)
File "*************\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "*************\pytorch-cifar100\pytorch-cifar100\models\vgg.py", line 40, in forward
output = self.classifier(output)
File "*************\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "*************\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
input = module(input)
File *************\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "*************\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
return F.linear(input, self.weight, self.bias)
File "*************\lib\site-packages\torch\nn\functional.py", line 1690, in linear
ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by starsky68** [comment]
> > If your dataset is a image classification dataset, you could implement your own dataset class to read your data.
> > see more details here:
> > https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset
> 
> I tried implement my dataset class, seems like loading goes well but there was an error when I trained, not sure whether you met this before, thanks in advance, here the message:
> 
> Traceback (most recent call last):
> File "train.py", line 209, in
> train(epoch)
> File "train.py", line 44, in train
> outputs = net(images)
> File "_************\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl result = self.forward(_input, **kwargs) File "_************\pytorch-cifar100\pytorch-cifar100\models\vgg.py", line 40, in forward output = self.classifier(output) File "_************\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl result = self.forward(_input, **kwargs) File "_************\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
> input = module(input)
> File _************\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl result = self.forward(_input, **kwargs) File "_************\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward return F.linear(input, self.weight, self.bias) File "_************\lib\site-packages\torch\nn\functional.py", line 1690, in linear
> ret = torch.addmm(bias, input, weight.t())
> RuntimeError: mat1 dim 1 must match mat2 dim 0

请检查一下你的output = self.classifier(output)前后，是否tensor的size发生了改变，tensor的形状要对齐

**Comment by ZhaolinWang0110** [comment]
use the function "torchvision.datasets.ImageFolder(root='path to your dir')" instead of function "torchvision.datasets.CIFAR100" in utils.py

**Comment by ZhaolinWang0110** [comment]
use the function "torchvision.datasets.ImageFolder(root='path to your dir')" instead of function "torchvision.datasets.CIFAR100" in utils.py

**Comment by ZhaolinWang0110** [comment]
use the function "torchvision.datasets.ImageFolder(root='path to your dir')" instead of function "torchvision.datasets.CIFAR100" in utils.py

**Comment by biel-wangdf3** [comment]
the cifar100 train image size:80*80, but when load train data only crop 32*32, 
    transform_train = transforms.Compose([
        #transforms.ToPILImage(),
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(15),
        transforms.ToTensor(),
        transforms.Normalize(mean, std)
    ])
test image size:32*32, didn't need to crop image;
When train your own datasets，you must keep train and test size equality, use the same transform!!!

**Comment by whisere** [comment]
How should we change if input image size is 100*100? Thanks!

**Comment by coisin-i** [comment]
My dataset is a csv file. How to change it
