### ISSUE TITLE
error when training, using the CIFAR100 dataset writing by dataset.py

### ISSUE THREAD

**Issue by lqin0818** [weiaicunzai/pytorch-cifar100#92]
Traceback (most recent call last):
  File "D:/Study/VGG/train.py", line 190, in <module>
    train(epoch)
  File "D:/Study/VGG/train.py", line 30, in train
    outputs = net(images)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Study\VGG\vgg_m.py", line 34, in forward
    x = self.features(x)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\qinli\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (__int64) and bias type (float) should be the same

**Comment by lqin0818** [comment]
the model used was VGG11

**Comment by EarlyBloomer-byte** [comment]
Yeah, VGG11 was used. Check the READme for more information.
